-- -------------------------------------------------------------
--
-- Module: filter
--
-- Generated by MATLAB(R) 7.9 and the Filter Design HDL Coder 2.5.
--
-- Generated on: 2015-01-13 11:34:48
--
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ResetType: Synchronous
-- TargetDirectory: C:\Users\ienny\Documents\GitHub\FM_Reciver\src
-- TestBenchStimulus: step ramp chirp 
--
-- Filter Settings:
--
-- Discrete-Time IIR Filter (real)
-- -------------------------------
-- Filter Structure    : Direct-Form II, Second-Order Sections
-- Number of Sections  : 9
-- Stable              : No
-- Linear Phase        : No
-- Arithmetic          : fixed
-- Numerator           : s12,10 -> [-2 2)
-- Denominator         : s12,10 -> [-2 2)
-- Scale Values        : s12,11 -> [-1 1)
-- Input               : s12,15 -> [-6.250000e-002 6.250000e-002)
-- Section Input       : s16,10 -> [-32 32)
-- Section Output      : s16,11 -> [-16 16)
-- Output              : s26,21 -> [-16 16)
-- State               : s16,15 -> [-1 1)
-- Numerator Prod      : s28,25 -> [-4 4)
-- Denominator Prod    : s28,25 -> [-4 4)
-- Numerator Accum     : s30,25 -> [-16 16)
-- Denominator Accum   : s30,25 -> [-16 16)
-- Round Mode          : convergent
-- Overflow Mode       : wrap
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(11 DOWNTO 0); -- sfix12_En15
         filter_out                      :   OUT   std_logic_vector(25 DOWNTO 0)  -- sfix26_En21
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT scaleconst1                    : signed(11 DOWNTO 0) := to_signed(172, 12); -- sfix12_En11
  CONSTANT coeff_b1_section1              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section1              : signed(11 DOWNTO 0) := to_signed(-2046, 12); -- sfix12_En10
  CONSTANT coeff_b3_section1              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section1              : signed(11 DOWNTO 0) := to_signed(-2043, 12); -- sfix12_En10
  CONSTANT coeff_a3_section1              : signed(11 DOWNTO 0) := to_signed(1019, 12); -- sfix12_En10
  CONSTANT scaleconst2                    : signed(11 DOWNTO 0) := to_signed(172, 12); -- sfix12_En11
  CONSTANT coeff_b1_section2              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section2              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_b3_section2              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section2              : signed(11 DOWNTO 0) := to_signed(-2047, 12); -- sfix12_En10
  CONSTANT coeff_a3_section2              : signed(11 DOWNTO 0) := to_signed(1023, 12); -- sfix12_En10
  CONSTANT scaleconst3                    : signed(11 DOWNTO 0) := to_signed(1036, 12); -- sfix12_En11
  CONSTANT coeff_b1_section3              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section3              : signed(11 DOWNTO 0) := to_signed(-2047, 12); -- sfix12_En10
  CONSTANT coeff_b3_section3              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section3              : signed(11 DOWNTO 0) := to_signed(-2045, 12); -- sfix12_En10
  CONSTANT coeff_a3_section3              : signed(11 DOWNTO 0) := to_signed(1021, 12); -- sfix12_En10
  CONSTANT scaleconst4                    : signed(11 DOWNTO 0) := to_signed(1036, 12); -- sfix12_En11
  CONSTANT coeff_b1_section4              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section4              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_b3_section4              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section4              : signed(11 DOWNTO 0) := to_signed(-2047, 12); -- sfix12_En10
  CONSTANT coeff_a3_section4              : signed(11 DOWNTO 0) := to_signed(1023, 12); -- sfix12_En10
  CONSTANT scaleconst5                    : signed(11 DOWNTO 0) := to_signed(1519, 12); -- sfix12_En11
  CONSTANT coeff_b1_section5              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section5              : signed(11 DOWNTO 0) := to_signed(-2047, 12); -- sfix12_En10
  CONSTANT coeff_b3_section5              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section5              : signed(11 DOWNTO 0) := to_signed(-2046, 12); -- sfix12_En10
  CONSTANT coeff_a3_section5              : signed(11 DOWNTO 0) := to_signed(1023, 12); -- sfix12_En10
  CONSTANT scaleconst6                    : signed(11 DOWNTO 0) := to_signed(1519, 12); -- sfix12_En11
  CONSTANT coeff_b1_section6              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section6              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_b3_section6              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section6              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_a3_section6              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT scaleconst7                    : signed(11 DOWNTO 0) := to_signed(1738, 12); -- sfix12_En11
  CONSTANT coeff_b1_section7              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section7              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_b3_section7              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section7              : signed(11 DOWNTO 0) := to_signed(-2047, 12); -- sfix12_En10
  CONSTANT coeff_a3_section7              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT scaleconst8                    : signed(11 DOWNTO 0) := to_signed(1738, 12); -- sfix12_En11
  CONSTANT coeff_b1_section8              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section8              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_b3_section8              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section8              : signed(11 DOWNTO 0) := to_signed(-2048, 12); -- sfix12_En10
  CONSTANT coeff_a3_section8              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT scaleconst9                    : signed(11 DOWNTO 0) := to_signed(18, 12); -- sfix12_En11
  CONSTANT coeff_b1_section9              : signed(11 DOWNTO 0) := to_signed(1024, 12); -- sfix12_En10
  CONSTANT coeff_b2_section9              : signed(11 DOWNTO 0) := to_signed(0, 12); -- sfix12_En10
  CONSTANT coeff_b3_section9              : signed(11 DOWNTO 0) := to_signed(-1024, 12); -- sfix12_En10
  CONSTANT coeff_a2_section9              : signed(11 DOWNTO 0) := to_signed(-2044, 12); -- sfix12_En10
  CONSTANT coeff_a3_section9              : signed(11 DOWNTO 0) := to_signed(1020, 12); -- sfix12_En10
  -- Signals
  SIGNAL input_register                   : signed(11 DOWNTO 0); -- sfix12_En15
  SIGNAL scale1                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp                         : signed(23 DOWNTO 0); -- sfix24_En26
  SIGNAL scaletypeconvert1                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum1                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum1                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum1                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert1                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv1                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul1                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul1                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul1                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul1                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul1                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL sub_cast                         : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_1                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp                         : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_2                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_3                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_1                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert1                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast                         : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_1                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp                         : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_2                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_3                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_1                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result1                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale2                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_1                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert2                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum2                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum2                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum2                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert2                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv2                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul2                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul2                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul2                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul2                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul2                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL mulpwr2_temp                     : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_4                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_5                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_2                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_6                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_7                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_3                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert2                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_4                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_5                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_2                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_6                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_7                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_3                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result2                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale3                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_2                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert3                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum3                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum3                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum3                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert3                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv3                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul3                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul3                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul3                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul3                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul3                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL sub_cast_8                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_9                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_4                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_10                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_11                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_5                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert3                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_8                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_9                       : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_4                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_10                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_11                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_5                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result3                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale4                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_3                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert4                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum4                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum4                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum4                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert4                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv4                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul4                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul4                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul4                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul4                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul4                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL mulpwr2_temp_1                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_12                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_13                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_6                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_14                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_15                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_7                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert4                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_12                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_13                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_6                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_14                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_15                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_7                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result4                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale5                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_4                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert5                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 5 Signals 
  SIGNAL a1sum5                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum5                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum5                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum5                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert5                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section5                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv5                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul5                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul5                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul5                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul5                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul5                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL sub_cast_16                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_17                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_8                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_18                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_19                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_9                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert5                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_16                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_17                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_8                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_18                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_19                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_9                       : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result5                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale6                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_5                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert6                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 6 Signals 
  SIGNAL a1sum6                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum6                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum6                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum6                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert6                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section6                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv6                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul6                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul6                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul6                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul6                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul6                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL mulpwr2_temp_2                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL mulpwr2_temp_3                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_20                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_21                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_10                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_22                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_23                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_11                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert6                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_20                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_21                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_10                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_22                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_23                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_11                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result6                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale7                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_6                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert7                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 7 Signals 
  SIGNAL a1sum7                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum7                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum7                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum7                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert7                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section7                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv7                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul7                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul7                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul7                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul7                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul7                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL mulpwr2_temp_4                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_24                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_25                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_12                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_26                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_27                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_13                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert7                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_24                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_25                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_12                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_26                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_27                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_13                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result7                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale8                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_7                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert8                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 8 Signals 
  SIGNAL a1sum8                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum8                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum8                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b2sum8                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert8                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section8                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv8                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul8                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul8                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul8                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b2mul8                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul8                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL mulpwr2_temp_5                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL mulpwr2_temp_6                   : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_28                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_29                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_14                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_30                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_31                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_15                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert8                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_28                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_29                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_14                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL add_cast_30                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_31                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_15                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL section_result8                  : signed(15 DOWNTO 0); -- sfix16_En11
  SIGNAL scale9                           : signed(31 DOWNTO 0); -- sfix32_En26
  SIGNAL mul_temp_8                       : signed(27 DOWNTO 0); -- sfix28_En22
  SIGNAL scaletypeconvert9                : signed(15 DOWNTO 0); -- sfix16_En10
  -- Section 9 Signals 
  SIGNAL a1sum9                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL a2sum9                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL b1sum9                           : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL typeconvert9                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section9                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv9                       : signed(15 DOWNTO 0); -- sfix16_En10
  SIGNAL a2mul9                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL a3mul9                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b1mul9                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL b3mul9                           : signed(27 DOWNTO 0); -- sfix28_En25
  SIGNAL unaryminus_temp                  : signed(16 DOWNTO 0); -- sfix17_En15
  SIGNAL sub_cast_32                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_33                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_16                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL sub_cast_34                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_cast_35                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL sub_temp_17                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL b1multypeconvert9                : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_32                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_cast_33                      : signed(29 DOWNTO 0); -- sfix30_En25
  SIGNAL add_temp_16                      : signed(30 DOWNTO 0); -- sfix31_En25
  SIGNAL output_typeconvert               : signed(25 DOWNTO 0); -- sfix26_En21
  SIGNAL output_register                  : signed(25 DOWNTO 0); -- sfix26_En21


BEGIN

  -- Block Statements
  input_reg_process : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        input_register <= (OTHERS => '0');
      ELSIF clk_enable = '1' THEN
        input_register <= signed(filter_in);
      END IF;
    END IF; 
  END PROCESS input_reg_process;

  mul_temp <= input_register * scaleconst1;
  scale1 <= resize(mul_temp, 32);

  scaletypeconvert1 <= resize(shift_right(scale1(31 DOWNTO 0) + ( "0" & (scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16) & NOT scale1(16))), 16), 16);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(25 DOWNTO 0) + ( "0" & (a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10) & NOT a1sum1(10))), 10), 16);

  delay_process_section1 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section1 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= scaletypeconvert1;

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= resize(typeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b2mul1 <= delay_section1(0) * coeff_b2_section1;

  b3mul1 <= resize(delay_section1(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast <= resize(inputconv1(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_1 <= resize(a2mul1, 30);
  sub_temp <= resize(sub_cast, 31) - resize(sub_cast_1, 31);
  a2sum1 <= sub_temp(29 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(a3mul1, 30);
  sub_temp_1 <= resize(sub_cast_2, 31) - resize(sub_cast_3, 31);
  a1sum1 <= sub_temp_1(29 DOWNTO 0);

  b1multypeconvert1 <= resize(b1mul1, 30);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(b2mul1, 30);
  add_temp <= resize(add_cast, 31) + resize(add_cast_1, 31);
  b2sum1 <= add_temp(29 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(b3mul1, 30);
  add_temp_1 <= resize(add_cast_2, 31) + resize(add_cast_3, 31);
  b1sum1 <= add_temp_1(29 DOWNTO 0);

  section_result1 <= resize(shift_right(b1sum1(29 DOWNTO 0) + ( "0" & (b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14) & NOT b1sum1(14))), 14), 16);

  mul_temp_1 <= section_result1 * scaleconst2;
  scale2 <= resize(mul_temp_1(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert2 <= resize(shift_right(scale2(31 DOWNTO 0) + ( "0" & (scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16) & NOT scale2(16))), 16), 16);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(25 DOWNTO 0) + ( "0" & (a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10) & NOT a1sum2(10))), 10), 16);

  delay_process_section2 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section2 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= scaletypeconvert2;

  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b1mul2 <= resize(typeconvert2(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  mulpwr2_temp <= ('0' & delay_section2(0)) WHEN delay_section2(0) = "1000000000000000"
      ELSE -resize(delay_section2(0),17);

  b2mul2 <= resize(mulpwr2_temp(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b3mul2 <= resize(delay_section2(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_4 <= resize(inputconv2(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_5 <= resize(a2mul2, 30);
  sub_temp_2 <= resize(sub_cast_4, 31) - resize(sub_cast_5, 31);
  a2sum2 <= sub_temp_2(29 DOWNTO 0);

  sub_cast_6 <= a2sum2;
  sub_cast_7 <= resize(a3mul2, 30);
  sub_temp_3 <= resize(sub_cast_6, 31) - resize(sub_cast_7, 31);
  a1sum2 <= sub_temp_3(29 DOWNTO 0);

  b1multypeconvert2 <= resize(b1mul2, 30);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(b2mul2, 30);
  add_temp_2 <= resize(add_cast_4, 31) + resize(add_cast_5, 31);
  b2sum2 <= add_temp_2(29 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(b3mul2, 30);
  add_temp_3 <= resize(add_cast_6, 31) + resize(add_cast_7, 31);
  b1sum2 <= add_temp_3(29 DOWNTO 0);

  section_result2 <= resize(shift_right(b1sum2(29 DOWNTO 0) + ( "0" & (b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14) & NOT b1sum2(14))), 14), 16);

  mul_temp_2 <= section_result2 * scaleconst3;
  scale3 <= resize(mul_temp_2(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert3 <= resize(shift_right(scale3(31 DOWNTO 0) + ( "0" & (scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16) & NOT scale3(16))), 16), 16);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(25 DOWNTO 0) + ( "0" & (a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10) & NOT a1sum3(10))), 10), 16);

  delay_process_section3 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section3 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= scaletypeconvert3;

  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b1mul3 <= resize(typeconvert3(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b2mul3 <= delay_section3(0) * coeff_b2_section3;

  b3mul3 <= resize(delay_section3(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_8 <= resize(inputconv3(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_9 <= resize(a2mul3, 30);
  sub_temp_4 <= resize(sub_cast_8, 31) - resize(sub_cast_9, 31);
  a2sum3 <= sub_temp_4(29 DOWNTO 0);

  sub_cast_10 <= a2sum3;
  sub_cast_11 <= resize(a3mul3, 30);
  sub_temp_5 <= resize(sub_cast_10, 31) - resize(sub_cast_11, 31);
  a1sum3 <= sub_temp_5(29 DOWNTO 0);

  b1multypeconvert3 <= resize(b1mul3, 30);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(b2mul3, 30);
  add_temp_4 <= resize(add_cast_8, 31) + resize(add_cast_9, 31);
  b2sum3 <= add_temp_4(29 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(b3mul3, 30);
  add_temp_5 <= resize(add_cast_10, 31) + resize(add_cast_11, 31);
  b1sum3 <= add_temp_5(29 DOWNTO 0);

  section_result3 <= resize(shift_right(b1sum3(29 DOWNTO 0) + ( "0" & (b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14) & NOT b1sum3(14))), 14), 16);

  mul_temp_3 <= section_result3 * scaleconst4;
  scale4 <= resize(mul_temp_3(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert4 <= resize(shift_right(scale4(31 DOWNTO 0) + ( "0" & (scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16) & NOT scale4(16))), 16), 16);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(25 DOWNTO 0) + ( "0" & (a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10) & NOT a1sum4(10))), 10), 16);

  delay_process_section4 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section4 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= scaletypeconvert4;

  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b1mul4 <= resize(typeconvert4(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  mulpwr2_temp_1 <= ('0' & delay_section4(0)) WHEN delay_section4(0) = "1000000000000000"
      ELSE -resize(delay_section4(0),17);

  b2mul4 <= resize(mulpwr2_temp_1(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b3mul4 <= resize(delay_section4(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_12 <= resize(inputconv4(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_13 <= resize(a2mul4, 30);
  sub_temp_6 <= resize(sub_cast_12, 31) - resize(sub_cast_13, 31);
  a2sum4 <= sub_temp_6(29 DOWNTO 0);

  sub_cast_14 <= a2sum4;
  sub_cast_15 <= resize(a3mul4, 30);
  sub_temp_7 <= resize(sub_cast_14, 31) - resize(sub_cast_15, 31);
  a1sum4 <= sub_temp_7(29 DOWNTO 0);

  b1multypeconvert4 <= resize(b1mul4, 30);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(b2mul4, 30);
  add_temp_6 <= resize(add_cast_12, 31) + resize(add_cast_13, 31);
  b2sum4 <= add_temp_6(29 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(b3mul4, 30);
  add_temp_7 <= resize(add_cast_14, 31) + resize(add_cast_15, 31);
  b1sum4 <= add_temp_7(29 DOWNTO 0);

  section_result4 <= resize(shift_right(b1sum4(29 DOWNTO 0) + ( "0" & (b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14) & NOT b1sum4(14))), 14), 16);

  mul_temp_4 <= section_result4 * scaleconst5;
  scale5 <= resize(mul_temp_4(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert5 <= resize(shift_right(scale5(31 DOWNTO 0) + ( "0" & (scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16) & NOT scale5(16))), 16), 16);

  --   ------------------ Section 5 ------------------

  typeconvert5 <= resize(shift_right(a1sum5(25 DOWNTO 0) + ( "0" & (a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10) & NOT a1sum5(10))), 10), 16);

  delay_process_section5 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section5 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section5(1) <= delay_section5(0);
        delay_section5(0) <= typeconvert5;
      END IF;
    END IF;
  END PROCESS delay_process_section5;

  inputconv5 <= scaletypeconvert5;

  a2mul5 <= delay_section5(0) * coeff_a2_section5;

  a3mul5 <= delay_section5(1) * coeff_a3_section5;

  b1mul5 <= resize(typeconvert5(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b2mul5 <= delay_section5(0) * coeff_b2_section5;

  b3mul5 <= resize(delay_section5(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_16 <= resize(inputconv5(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_17 <= resize(a2mul5, 30);
  sub_temp_8 <= resize(sub_cast_16, 31) - resize(sub_cast_17, 31);
  a2sum5 <= sub_temp_8(29 DOWNTO 0);

  sub_cast_18 <= a2sum5;
  sub_cast_19 <= resize(a3mul5, 30);
  sub_temp_9 <= resize(sub_cast_18, 31) - resize(sub_cast_19, 31);
  a1sum5 <= sub_temp_9(29 DOWNTO 0);

  b1multypeconvert5 <= resize(b1mul5, 30);

  add_cast_16 <= b1multypeconvert5;
  add_cast_17 <= resize(b2mul5, 30);
  add_temp_8 <= resize(add_cast_16, 31) + resize(add_cast_17, 31);
  b2sum5 <= add_temp_8(29 DOWNTO 0);

  add_cast_18 <= b2sum5;
  add_cast_19 <= resize(b3mul5, 30);
  add_temp_9 <= resize(add_cast_18, 31) + resize(add_cast_19, 31);
  b1sum5 <= add_temp_9(29 DOWNTO 0);

  section_result5 <= resize(shift_right(b1sum5(29 DOWNTO 0) + ( "0" & (b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14) & NOT b1sum5(14))), 14), 16);

  mul_temp_5 <= section_result5 * scaleconst6;
  scale6 <= resize(mul_temp_5(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert6 <= resize(shift_right(scale6(31 DOWNTO 0) + ( "0" & (scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16) & NOT scale6(16))), 16), 16);

  --   ------------------ Section 6 ------------------

  typeconvert6 <= resize(shift_right(a1sum6(25 DOWNTO 0) + ( "0" & (a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10) & NOT a1sum6(10))), 10), 16);

  delay_process_section6 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section6 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section6(1) <= delay_section6(0);
        delay_section6(0) <= typeconvert6;
      END IF;
    END IF;
  END PROCESS delay_process_section6;

  inputconv6 <= scaletypeconvert6;

  mulpwr2_temp_2 <= ('0' & delay_section6(0)) WHEN delay_section6(0) = "1000000000000000"
      ELSE -resize(delay_section6(0),17);

  a2mul6 <= resize(mulpwr2_temp_2(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  a3mul6 <= resize(delay_section6(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b1mul6 <= resize(typeconvert6(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  mulpwr2_temp_3 <= ('0' & delay_section6(0)) WHEN delay_section6(0) = "1000000000000000"
      ELSE -resize(delay_section6(0),17);

  b2mul6 <= resize(mulpwr2_temp_3(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b3mul6 <= resize(delay_section6(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_20 <= resize(inputconv6(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_21 <= resize(a2mul6, 30);
  sub_temp_10 <= resize(sub_cast_20, 31) - resize(sub_cast_21, 31);
  a2sum6 <= sub_temp_10(29 DOWNTO 0);

  sub_cast_22 <= a2sum6;
  sub_cast_23 <= resize(a3mul6, 30);
  sub_temp_11 <= resize(sub_cast_22, 31) - resize(sub_cast_23, 31);
  a1sum6 <= sub_temp_11(29 DOWNTO 0);

  b1multypeconvert6 <= resize(b1mul6, 30);

  add_cast_20 <= b1multypeconvert6;
  add_cast_21 <= resize(b2mul6, 30);
  add_temp_10 <= resize(add_cast_20, 31) + resize(add_cast_21, 31);
  b2sum6 <= add_temp_10(29 DOWNTO 0);

  add_cast_22 <= b2sum6;
  add_cast_23 <= resize(b3mul6, 30);
  add_temp_11 <= resize(add_cast_22, 31) + resize(add_cast_23, 31);
  b1sum6 <= add_temp_11(29 DOWNTO 0);

  section_result6 <= resize(shift_right(b1sum6(29 DOWNTO 0) + ( "0" & (b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14) & NOT b1sum6(14))), 14), 16);

  mul_temp_6 <= section_result6 * scaleconst7;
  scale7 <= resize(mul_temp_6(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert7 <= resize(shift_right(scale7(31 DOWNTO 0) + ( "0" & (scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16) & NOT scale7(16))), 16), 16);

  --   ------------------ Section 7 ------------------

  typeconvert7 <= resize(shift_right(a1sum7(25 DOWNTO 0) + ( "0" & (a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10) & NOT a1sum7(10))), 10), 16);

  delay_process_section7 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section7 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section7(1) <= delay_section7(0);
        delay_section7(0) <= typeconvert7;
      END IF;
    END IF;
  END PROCESS delay_process_section7;

  inputconv7 <= scaletypeconvert7;

  a2mul7 <= delay_section7(0) * coeff_a2_section7;

  a3mul7 <= resize(delay_section7(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b1mul7 <= resize(typeconvert7(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  mulpwr2_temp_4 <= ('0' & delay_section7(0)) WHEN delay_section7(0) = "1000000000000000"
      ELSE -resize(delay_section7(0),17);

  b2mul7 <= resize(mulpwr2_temp_4(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b3mul7 <= resize(delay_section7(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_24 <= resize(inputconv7(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_25 <= resize(a2mul7, 30);
  sub_temp_12 <= resize(sub_cast_24, 31) - resize(sub_cast_25, 31);
  a2sum7 <= sub_temp_12(29 DOWNTO 0);

  sub_cast_26 <= a2sum7;
  sub_cast_27 <= resize(a3mul7, 30);
  sub_temp_13 <= resize(sub_cast_26, 31) - resize(sub_cast_27, 31);
  a1sum7 <= sub_temp_13(29 DOWNTO 0);

  b1multypeconvert7 <= resize(b1mul7, 30);

  add_cast_24 <= b1multypeconvert7;
  add_cast_25 <= resize(b2mul7, 30);
  add_temp_12 <= resize(add_cast_24, 31) + resize(add_cast_25, 31);
  b2sum7 <= add_temp_12(29 DOWNTO 0);

  add_cast_26 <= b2sum7;
  add_cast_27 <= resize(b3mul7, 30);
  add_temp_13 <= resize(add_cast_26, 31) + resize(add_cast_27, 31);
  b1sum7 <= add_temp_13(29 DOWNTO 0);

  section_result7 <= resize(shift_right(b1sum7(29 DOWNTO 0) + ( "0" & (b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14) & NOT b1sum7(14))), 14), 16);

  mul_temp_7 <= section_result7 * scaleconst8;
  scale8 <= resize(mul_temp_7(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert8 <= resize(shift_right(scale8(31 DOWNTO 0) + ( "0" & (scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16) & NOT scale8(16))), 16), 16);

  --   ------------------ Section 8 ------------------

  typeconvert8 <= resize(shift_right(a1sum8(25 DOWNTO 0) + ( "0" & (a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10) & NOT a1sum8(10))), 10), 16);

  delay_process_section8 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section8 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section8(1) <= delay_section8(0);
        delay_section8(0) <= typeconvert8;
      END IF;
    END IF;
  END PROCESS delay_process_section8;

  inputconv8 <= scaletypeconvert8;

  mulpwr2_temp_5 <= ('0' & delay_section8(0)) WHEN delay_section8(0) = "1000000000000000"
      ELSE -resize(delay_section8(0),17);

  a2mul8 <= resize(mulpwr2_temp_5(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  a3mul8 <= resize(delay_section8(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b1mul8 <= resize(typeconvert8(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  mulpwr2_temp_6 <= ('0' & delay_section8(0)) WHEN delay_section8(0) = "1000000000000000"
      ELSE -resize(delay_section8(0),17);

  b2mul8 <= resize(mulpwr2_temp_6(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  b3mul8 <= resize(delay_section8(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_28 <= resize(inputconv8(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_29 <= resize(a2mul8, 30);
  sub_temp_14 <= resize(sub_cast_28, 31) - resize(sub_cast_29, 31);
  a2sum8 <= sub_temp_14(29 DOWNTO 0);

  sub_cast_30 <= a2sum8;
  sub_cast_31 <= resize(a3mul8, 30);
  sub_temp_15 <= resize(sub_cast_30, 31) - resize(sub_cast_31, 31);
  a1sum8 <= sub_temp_15(29 DOWNTO 0);

  b1multypeconvert8 <= resize(b1mul8, 30);

  add_cast_28 <= b1multypeconvert8;
  add_cast_29 <= resize(b2mul8, 30);
  add_temp_14 <= resize(add_cast_28, 31) + resize(add_cast_29, 31);
  b2sum8 <= add_temp_14(29 DOWNTO 0);

  add_cast_30 <= b2sum8;
  add_cast_31 <= resize(b3mul8, 30);
  add_temp_15 <= resize(add_cast_30, 31) + resize(add_cast_31, 31);
  b1sum8 <= add_temp_15(29 DOWNTO 0);

  section_result8 <= resize(shift_right(b1sum8(29 DOWNTO 0) + ( "0" & (b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14) & NOT b1sum8(14))), 14), 16);

  mul_temp_8 <= section_result8 * scaleconst9;
  scale9 <= resize(mul_temp_8(27 DOWNTO 0) & '0' & '0' & '0' & '0', 32);

  scaletypeconvert9 <= resize(shift_right(scale9(31 DOWNTO 0) + ( "0" & (scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16) & NOT scale9(16))), 16), 16);

  --   ------------------ Section 9 ------------------

  typeconvert9 <= resize(shift_right(a1sum9(25 DOWNTO 0) + ( "0" & (a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10) & NOT a1sum9(10))), 10), 16);

  delay_process_section9 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        delay_section9 <= (OTHERS => (OTHERS => '0'));
      ELSIF clk_enable = '1' THEN
        delay_section9(1) <= delay_section9(0);
        delay_section9(0) <= typeconvert9;
      END IF;
    END IF;
  END PROCESS delay_process_section9;

  inputconv9 <= scaletypeconvert9;

  a2mul9 <= delay_section9(0) * coeff_a2_section9;

  a3mul9 <= delay_section9(1) * coeff_a3_section9;

  b1mul9 <= resize(typeconvert9(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  unaryminus_temp <= ('0' & delay_section9(1)) WHEN delay_section9(1) = "1000000000000000"
      ELSE -resize(delay_section9(1),17);
  b3mul9 <= resize(unaryminus_temp(16 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 28);

  sub_cast_32 <= resize(inputconv9(14 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 30);
  sub_cast_33 <= resize(a2mul9, 30);
  sub_temp_16 <= resize(sub_cast_32, 31) - resize(sub_cast_33, 31);
  a2sum9 <= sub_temp_16(29 DOWNTO 0);

  sub_cast_34 <= a2sum9;
  sub_cast_35 <= resize(a3mul9, 30);
  sub_temp_17 <= resize(sub_cast_34, 31) - resize(sub_cast_35, 31);
  a1sum9 <= sub_temp_17(29 DOWNTO 0);

  b1multypeconvert9 <= resize(b1mul9, 30);

  add_cast_32 <= b1multypeconvert9;
  add_cast_33 <= resize(b3mul9, 30);
  add_temp_16 <= resize(add_cast_32, 31) + resize(add_cast_33, 31);
  b1sum9 <= add_temp_16(29 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum9(29 DOWNTO 0) + ( "0" & (b1sum9(4) & NOT b1sum9(4) & NOT b1sum9(4) & NOT b1sum9(4))), 4), 26);

  Output_Register_process : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        output_register <= (OTHERS => '0');
      ELSIF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
